#!/bin/bash

# Script to help update imports in the codebase

echo "This script will help you update imports in your codebase."
echo "Here are the import patterns you should use:"
echo ""
echo "Old import pattern                       New import pattern"
echo "--------------------------------------------------------------"
echo "@/components/ui/button                   @/core/components/ui/button"
echo "@/components/ui                          @/core/components/ui"
echo "@/components/layout/Navbar               @/core/components/layout/Navbar"
echo "@/components/layout                      @/core/components/layout"
echo "@/components/bars/BarCard                @/features/bars/components/BarCard"
echo "@/components/bars                        @/features/bars/components"
echo "@/components/map/SimpleMap               @/features/maps/components/SimpleMap"
echo "@/components/map                         @/features/maps/components"
echo "@/hooks/useBarData                       @/features/bars/hooks/useBarData"
echo "@/utils/bar-utils                        @/features/bars/utils/bar-utils"
echo "@/utils/animation-utils                  @/core/utils/animation-utils"
echo ""
echo "You can use the following commands to find files that need to be updated:"
echo ""
echo "# Find files that import from @/components/ui"
echo "grep -r \"@/components/ui\" --include=\"*.tsx\" --include=\"*.ts\" src"
echo ""
echo "# Find files that import from @/components/layout"
echo "grep -r \"@/components/layout\" --include=\"*.tsx\" --include=\"*.ts\" src"
echo ""
echo "# Find files that import from @/components/bars"
echo "grep -r \"@/components/bars\" --include=\"*.tsx\" --include=\"*.ts\" src"
echo ""
echo "# Find files that import from @/components/map"
echo "grep -r \"@/components/map\" --include=\"*.tsx\" --include=\"*.ts\" src"
echo ""
echo "# Find files that import from @/hooks"
echo "grep -r \"@/hooks\" --include=\"*.tsx\" --include=\"*.ts\" src"
echo ""
echo "# Find files that import from @/utils"
echo "grep -r \"@/utils\" --include=\"*.tsx\" --include=\"*.ts\" src"
echo ""
echo "You can use the following commands to update imports:"
echo ""
echo "# Update imports from @/components/ui to @/core/components/ui"
echo "find src -type f -name \"*.tsx\" -o -name \"*.ts\" | xargs sed -i '' 's|@/components/ui|@/core/components/ui|g'"
echo ""
echo "# Update imports from @/components/layout to @/core/components/layout"
echo "find src -type f -name \"*.tsx\" -o -name \"*.ts\" | xargs sed -i '' 's|@/components/layout|@/core/components/layout|g'"
echo ""
echo "# Update imports from @/components/bars to @/features/bars/components"
echo "find src -type f -name \"*.tsx\" -o -name \"*.ts\" | xargs sed -i '' 's|@/components/bars|@/features/bars/components|g'"
echo ""
echo "# Update imports from @/components/map to @/features/maps/components"
echo "find src -type f -name \"*.tsx\" -o -name \"*.ts\" | xargs sed -i '' 's|@/components/map|@/features/maps/components|g'"
echo ""
echo "# Update imports from @/hooks/useBarData to @/features/bars/hooks/useBarData"
echo "find src -type f -name \"*.tsx\" -o -name \"*.ts\" | xargs sed -i '' 's|@/hooks/useBarData|@/features/bars/hooks/useBarData|g'"
echo ""
echo "# Update imports from @/utils/bar-utils to @/features/bars/utils/bar-utils"
echo "find src -type f -name \"*.tsx\" -o -name \"*.ts\" | xargs sed -i '' 's|@/utils/bar-utils|@/features/bars/utils/bar-utils|g'"
echo ""
echo "# Update imports from @/utils/animation-utils to @/core/utils/animation-utils"
echo "find src -type f -name \"*.tsx\" -o -name \"*.ts\" | xargs sed -i '' 's|@/utils/animation-utils|@/core/utils/animation-utils|g'"
echo ""
echo "# Update imports from @/utils/date-utils to @/core/utils/date-utils"
echo "find src -type f -name \"*.tsx\" -o -name \"*.ts\" | xargs sed -i '' 's|@/utils/date-utils|@/core/utils/date-utils|g'"
echo ""
echo "After updating imports, test the application to ensure everything works."
